import Head from "next/head";
import type { NextPage } from "next";
import Masthead from "@/components/masthead";

const Home: NextPage = () =>{
  return(
    <div>
      <Head>
        <title>newFlow</title>
        <meta name='newname' content='Generated by newflow'/>
      </Head>
      <Masthead/>
    </div>
  )
}

export default Home;

